routes:
  html:
    config:
      prefix: "tested-here"
      renderFrom: "randomFloat"
    plugins:
      - sampleData
      - htmlRender
  json:
    config:
      renderFrom: "random"
    plugins:
      - sampleData
      - jsonRender
  todo:
    config:
      renderFrom: "httpRes"
      httpUrl: "http://jsonplaceholder.typicode.com/todos/"
    plugins:
      - httpSource
      - rawRender
  mongo:
    config:
      m2jFrom: mongoRes
      m2jTo: mongoJSON
      renderFrom: mongoJSON
      mongoCollection: test
      mongoDb: test
    plugins:
      - mongoSource
      - mapToJson
      - rawRender
