routes:
  html:
    config:
      prefix: "tested-here"
      renderFrom: "randomFloat"
    plugins:
      - sampleData
      - htmlRender
  json:
    config:
      renderFrom: "random"
    plugins:
      - sampleData
      - jsonRender
